# Generated by Django 4.2.16 on 2026-04-26 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='members',
            field=models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
