# Generated by Django 4.2.16 on 2025-05-27 23:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Número de cuota', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Fecha de vencimiento de la cuota', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la cuota', max_digits=12, null=True)),
                ('paid', models.BooleanField(default=False, help_text='Indica si la cuota ha sido pagada')),
                ('paid_on', models.DateField(blank=True, help_text='Fecha en la cual se realizó el pago', null=True)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monto aplicado a capital', max_digits=12, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monto aplicado a intereses', max_digits=12, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Recargo por mora si aplica', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fintech.credit')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('credit', 'number')},
            },
        ),
    ]
