# Generated by Django 4.2.16 on 2024-09-11 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AlterField(
            model_name='credit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
