# Generated by Django 3.2 on 2024-09-11 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0002_remove_role_group_alter_credit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fintech.subcategory'),
        ),
    ]
