# Generated by Django 4.2.16 on 2025-05-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0002_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='fintech.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='periodicity',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='fintech.periodicity'),
            preserve_default=False,
        ),
    ]
