# Generated by Django 3.2 on 2024-09-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='subcategory',
        ),
    ]
