# Generated by Django 4.2.16 on 2025-06-25 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0003_alter_credit_payment_alter_credit_periodicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Tasa base para esta categoría (%)', max_digits=5)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo permitido', max_digits=12, null=True)),
                ('max_term_days', models.IntegerField(blank=True, help_text='Plazo máximo en días', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_rate_config', to='fintech.subcategory')),
            ],
            options={
                'verbose_name': 'Categoría de Tasa de Interés',
                'verbose_name_plural': 'Categorías de Tasas de Interés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código de la fuente de la solicitud', unique=True)),
                ('name', models.CharField(help_text="Nombre de la fuente de la solicitud, por ejemplo: 'Web', 'App', 'Teléfono', 'Correo Electrónico', 'Chatbot', 'API', 'Chat'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción de la fuente de la solicitud', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la fuente de la solicitud está activo')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código del estado de la solicitud', unique=True)),
                ('name', models.CharField(help_text="Nombre del estado de la solicitud, por ejemplo: 'Pendiente', 'Aprobado', 'Cancelado','Rechazado'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del estado de la solicitud', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el estado de la solicitud está activo')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código del tipo de solicitud', unique=True)),
                ('name', models.CharField(help_text="Nombre del tipo de solicitud, Ejemplo: 'Solicitud de Crédito', 'Solicitud de Préstamo', 'Solicitud de Refinanciamiento', 'Soliciud de plazo fijo'", max_length=100)),
                ('requires_approval', models.BooleanField(default=True, help_text='Indica si la solicitud requiere aprobación')),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de solicitud', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el tipo de solicitud está activo')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código de la solicitud', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la solicitud.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización de la solicitud.')),
                ('notes', models.CharField(blank=True, help_text='Notas adicionales opcionales sobre la solicitud.', max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado a la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requests', to='fintech.requestsource')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requests', to='fintech.requeststatus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requests', to='fintech.requesttype')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso mensual del usuario.', max_digits=12, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Gastos mensuales del usuario.', max_digits=12, null=True)),
                ('monthly_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Ahorro mensual del usuario.', max_digits=12, null=True)),
                ('monthly_investments', models.DecimalField(blank=True, decimal_places=2, help_text='Inversiones mensuales del usuario.', max_digits=12, null=True)),
                ('monthly_debt', models.DecimalField(blank=True, decimal_places=2, help_text='Deuda mensual del usuario.', max_digits=12, null=True)),
                ('monthly_credit_payments', models.DecimalField(blank=True, decimal_places=2, help_text='Pagos de crédito mensuales del usuario.', max_digits=12, null=True)),
                ('income_source', models.CharField(blank=True, help_text='Fuente de ingresos del usuario.', max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Tiempo Completo'), ('PART_TIME', 'Medio Tiempo'), ('CONTRACTOR', 'Contratista'), ('SELF_EMPLOYED', 'Independiente'), ('UNEMPLOYED', 'Desempleado'), ('RETIRED', 'Jubilado')], help_text='Tipo de empleo del usuario.', max_length=20, null=True)),
                ('investment_experience', models.CharField(blank=True, help_text='Experiencia en inversiones del usuario.', max_length=255, null=True)),
                ('risk_tolerance', models.CharField(choices=[('VERY_LOW', 'Muy Bajo'), ('LOW', 'Bajo'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto'), ('VERY_HIGH', 'Muy Alto')], default='MODERATE', help_text='Tolerancia al riesgo del usuario.', max_length=20)),
                ('info_verified', models.BooleanField(default=False, help_text='Verificación de información del usuario')),
                ('can_request_credit', models.BooleanField(default=True, help_text='Indica si el usuario puede solicitar créditos')),
                ('debt_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Ratio deuda/ingreso calculado automáticamente', max_digits=5, null=True)),
                ('restriction_reason', models.TextField(blank=True, help_text='Razón por la cual el usuario tiene restricciones', null=True)),
                ('financial_health_score', models.IntegerField(blank=True, help_text='Puntaje de salud financiera (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='UserInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_rate', models.DecimalField(decimal_places=2, help_text='Tasa de interés personalizada para este usuario (%)', max_digits=5)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha desde la cual es efectiva la tasa')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Fecha de vencimiento de la tasa personalizada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Usuario que aprobó esta tasa personalizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rates', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rates', to='fintech.interestratecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de Interés de Usuario',
                'verbose_name_plural': 'Tasas de Interés de Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investement_amount', models.DecimalField(decimal_places=2, help_text='Monto que se desea invertir.', max_digits=12)),
                ('investment_horizon', models.IntegerField(help_text='Plazo de la inversión.')),
                ('risk_tolerance', models.CharField(help_text='Tolerancia al riesgo (Ej: conservador, moderado, arriesgado).', max_length=255)),
                ('investment_goal', models.CharField(help_text='Objetivo de la inversión (Ej: ahorro, aumentar patrimonio, etc).', max_length=255)),
                ('investor_type', models.CharField(help_text='Tipo de inversionista (Ej: conservador, arriesgado, estratégico).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el detalle de la solicitud.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización del detalle de la solicitud.')),
                ('request', models.OneToOneField(help_text='Referencia a la solicitud general de tipo inversión.', on_delete=django.db.models.deletion.CASCADE, related_name='investment_detail', to='fintech.userrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto solicitado para el crédito.', max_digits=12)),
                ('term_days', models.IntegerField(help_text='Plazo en días para el crédito.')),
                ('purpose', models.CharField(blank=True, choices=[('HOUSING', 'Vivienda'), ('VEHICLE', 'Vehículo'), ('EDUCATION', 'Educación'), ('INVESTMENT', 'Inversión'), ('PERSONAL', 'Personal'), ('DEBT_CONSOLIDATION', 'Consolidación de deuda'), ('BUSINESS', 'Negocio'), ('OTHER', 'Otro')], help_text='Propósito del crédito', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el detalle de la solicitud.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización del detalle de la solicitud.')),
                ('request', models.OneToOneField(help_text='Referencia a la solicitud general de tipo crédito.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_detail', to='fintech.userrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['user', 'type', 'status', 'source'], name='fintech_use_user_id_614b79_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['user', 'type', 'status', 'source', 'assigned_to'], name='fintech_use_user_id_8de275_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterestrate',
            unique_together={('user', 'category')},
        ),
    ]
