# Generated by Django 4.2.16 on 2025-07-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0004_interestratecategory_requestsource_requeststatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentrequestdetail',
            name='investor_type',
        ),
    ]
