# Generated by Django 4.2.16 on 2026-05-27 18:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0004_credit_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='late_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Tasa mensual de recargo por mora. Ej: 0.05 = 5% mensual. Configurable por crédito al momento de creación.', max_digits=5),
        ),
    ]
