# Generated by Django 4.2.16 on 2026-05-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0005_add_late_fee_rate_to_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_fee', models.DecimalField(decimal_places=2, help_text='Monto de recargo que el sistema calculó al momento de la decisión', max_digits=12)),
                ('applied_fee', models.DecimalField(decimal_places=2, help_text='Monto de recargo que realmente se cobró al cliente', max_digits=12)),
                ('decision', models.CharField(choices=[('applied', 'Aplicó recargo completo'), ('partial', 'Aplicó recargo parcial'), ('waived', 'Condonó recargo')], help_text='Tipo de decisión tomada sobre el recargo', max_length=10)),
                ('reason', models.TextField(blank=True, help_text="Justificación obligatoria cuando decision es 'partial' o 'waived'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(help_text='Cuota sobre la cual se tomó la decisión de recargo', on_delete=django.db.models.deletion.CASCADE, related_name='fee_decisions', to='fintech.installment')),
                ('seller', models.ForeignKey(blank=True, help_text='Cobrador que tomó la decisión. Null si fue registrada desde oficina.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_decisions', to='fintech.seller')),
            ],
            options={
                'verbose_name': 'Decisión de recargo',
                'verbose_name_plural': 'Decisiones de recargo',
                'ordering': ['-created_at'],
            },
        ),
    ]
