# Generated by Django 3.2 on 2024-09-12 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0005_auto_20240911_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_made_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
