# Generated by Django 4.2.16 on 2025-07-27 20:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0005_remove_investmentrequestdetail_investor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestratecategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='investmentrequestdetail',
            name='request',
        ),
        migrations.AlterUniqueTogether(
            name='userinterestrate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userinterestrate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='userinterestrate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userinterestrate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='source',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='installment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pagado hasta ahora', max_digits=12),
        ),
        migrations.AddField(
            model_name='installment',
            name='days_overdue',
            field=models.PositiveIntegerField(default=0, help_text='Días de mora'),
        ),
        migrations.AddField(
            model_name='installment',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Indica si está programada para pago automático'),
        ),
        migrations.AddField(
            model_name='installment',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, help_text='Fecha del último recordatorio', null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='next_reminder_date',
            field=models.DateTimeField(blank=True, help_text='Fecha del próximo recordatorio', null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Indica si se envió notificación'),
        ),
        migrations.AddField(
            model_name='installment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto restante por pagar', max_digits=12),
        ),
        migrations.AddField(
            model_name='installment',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de recordatorios enviados'),
        ),
        migrations.AddField(
            model_name='installment',
            name='scheduled_payment_date',
            field=models.DateField(blank=True, help_text='Fecha programada para pago automático', null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada'), ('partial', 'Pago Parcial')], default='pending', help_text='Estado actual de la cuota', max_length=20),
        ),
        migrations.DeleteModel(
            name='CreditRequestDetail',
        ),
        migrations.DeleteModel(
            name='InterestRateCategory',
        ),
        migrations.DeleteModel(
            name='InvestmentRequestDetail',
        ),
        migrations.DeleteModel(
            name='RequestSource',
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
        migrations.DeleteModel(
            name='RequestType',
        ),
        migrations.DeleteModel(
            name='UserInterestRate',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
