# Generated by Django 4.2.16 on 2025-08-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0006_remove_interestratecategory_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-created_at']},
        ),
    ]
