# Generated by Django 4.2.16 on 2025-01-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0008_alter_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fintech.seller'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App'), ('admin', 'Admin Panel'), ('import', 'Imported Data')], default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='confirmed', max_length=50),
        ),
    ]
