# Generated by Django 4.2.16 on 2025-09-06 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0008_alter_address_user_alter_credit_registered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_registered', to='auth.User'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='auth.User'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='auth.User'),
        ),
    ]
