# Generated by Django 4.2.16 on 2026-05-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fintech', '0004_credit_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('credit_delivery', 'Entrega de Crédito'), ('payment_full', 'Cobro completo'), ('payment_partial', 'Cobro parcial'), ('office_payment', 'Pago en oficina'), ('visit', 'Visita (sin cobro)'), ('promise', 'Promesa de pago'), ('call', 'Llamada')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_variance', models.IntegerField(blank=True, help_text='Distancia en metros al punto más cercano del cliente', null=True)),
                ('promise_date', models.DateField(blank=True, null=True)),
                ('promise_fulfilled', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('mobile', 'Dispositivo Móvil'), ('office', 'Oficina')], default='mobile', max_length=10)),
                ('captured_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('sync_lag_seconds', models.IntegerField(blank=True, null=True)),
                ('offline_sync', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='fintech.seller')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='fintech.credit')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_logs', to='fintech.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('credit_delivery', 'Desembolso'), ('visit', 'Visita'), ('payment', 'Cobro')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_points', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_point', to='interactions.interactionlog')),
            ],
        ),
    ]
