# Generated by Django 4.2.16 on 2025-05-21 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del tenant', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(blank=True, help_text='Identificador URL-friendly del tenant', max_length=100, unique=True)),
                ('contact_email', models.EmailField(help_text='Email principal para comunicaciones con el tenant', max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el tenant está activo')),
                ('is_trial', models.BooleanField(default=False, help_text='Indica si el tenant está en período de prueba')),
                ('trial_expiry_date', models.DateTimeField(blank=True, help_text='Fecha de expiración del período de prueba', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Número máximo de usuarios permitidos')),
                ('storage_limit_mb', models.PositiveIntegerField(default=1024, help_text='Límite de almacenamiento en MB')),
                ('current_storage_usage_mb', models.FloatField(default=0, help_text='Uso actual de almacenamiento en MB')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='Indica si es un rol del sistema (no puede ser eliminado)')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Permisos asociados a este rol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rol de tenant',
                'verbose_name_plural': 'Roles de tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_provider', models.CharField(blank=True, help_text='Proveedor de pagos (Stripe, PayPal, etc.)', max_length=50, null=True)),
                ('subscription_id', models.CharField(blank=True, help_text='ID de suscripción en el sistema de pagos', max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, help_text='ID de cliente en el sistema de pagos', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.subscriptionplan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.subscriptionstatus')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción de tenant',
                'verbose_name_plural': 'Suscripciones de tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='default', help_text='Tema visual del tenant', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Logo del tenant', null=True, upload_to='tenant_logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon del tenant', null=True, upload_to='tenant_favicons/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Color primario en formato hexadecimal', max_length=7)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Habilitar notificaciones por email')),
                ('time_zone', models.CharField(default='UTC', help_text='Zona horaria del tenant', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', help_text='Formato de fecha', max_length=20)),
                ('password_expiry_days', models.PositiveIntegerField(default=90, help_text='Días antes de expiración de contraseñas')),
                ('mfa_required', models.BooleanField(default=False, help_text='Requerir autenticación de dos factores')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Tiempo de expiración de sesión en minutos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Configuración de tenant',
                'verbose_name_plural': 'Configuraciones de tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('invite', 'Invitación'), ('join', 'Unirse'), ('leave', 'Salir'), ('payment', 'Pago'), ('subscription_change', 'Cambio de suscripción'), ('settings_change', 'Cambio de configuración'), ('api_access', 'Acceso API'), ('other', 'Otro')], max_length=30)),
                ('entity_type', models.CharField(blank=True, help_text='Tipo de entidad afectada', max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, help_text='ID de la entidad afectada', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Detalles adicionales de la acción', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenant.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo en este tenant')),
                ('invitation_accepted', models.BooleanField(default=False, help_text='Indica si el usuario ha aceptado la invitación')),
                ('invitation_sent_at', models.DateTimeField(blank=True, help_text='Fecha en que se envió la invitación', null=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, help_text='Fecha en que se aceptó la invitación', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.tenantrole')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de tenant',
                'verbose_name_plural': 'Membresías de tenant',
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='tenant.tenantinvitationrole')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Invitación de tenant',
                'verbose_name_plural': 'Invitaciones de tenant',
                'unique_together': {('tenant', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TenantApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para la clave API', max_length=100)),
                ('prefix', models.CharField(editable=False, help_text='Prefijo visible de la clave API', max_length=8)),
                ('key', models.CharField(editable=False, help_text='Clave API encriptada', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Clave API de tenant',
                'verbose_name_plural': 'Claves API de tenant',
                'unique_together': {('tenant', 'prefix')},
            },
        ),
    ]
