# Generated by Django 4.2.16 on 2025-08-08 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0006_remove_interestratecategory_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='nombre del patrón')),
                ('pattern_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('weekly', 'Semanal')], max_length=15, verbose_name='tipo de patrón')),
                ('description', models.TextField(help_text='Descripción detallada del patrón identificado', verbose_name='descripción')),
                ('peak_periods', models.JSONField(default=list, help_text='Períodos donde el patrón es más fuerte', verbose_name='períodos pico')),
                ('low_periods', models.JSONField(default=list, help_text='Períodos donde el patrón es más débil', verbose_name='períodos bajos')),
                ('amplitude', models.DecimalField(decimal_places=2, help_text='Diferencia entre picos y valles', max_digits=10, verbose_name='amplitud')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Qué tan confiable es este patrón (0-100)', max_digits=5, verbose_name='puntuación de confianza')),
                ('identified_from', models.DateField(help_text='Fecha desde la cual se identificó el patrón', verbose_name='identificado desde')),
                ('identified_to', models.DateField(help_text='Fecha hasta la cual se validó el patrón', verbose_name='identificado hasta')),
                ('next_expected_peak', models.DateField(blank=True, null=True, verbose_name='próximo pico esperado')),
                ('next_expected_low', models.DateField(blank=True, null=True, verbose_name='próximo valle esperado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'patrón estacional',
                'verbose_name_plural': 'patrones estacionales',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['pattern_type', 'confidence_score'], name='forecasting_pattern_ba70c9_idx'), models.Index(fields=['created_at'], name='forecasting_created_c8d8d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('credit_default', 'Riesgo de impago de crédito'), ('portfolio_concentration', 'Riesgo de concentración'), ('liquidity_risk', 'Riesgo de liquidez'), ('market_risk', 'Riesgo de mercado'), ('operational_risk', 'Riesgo operacional')], max_length=25, verbose_name='tipo de riesgo')),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=10, verbose_name='nivel de riesgo')),
                ('risk_score', models.DecimalField(decimal_places=2, help_text='0.00 = Sin riesgo, 100.00 = Riesgo máximo', max_digits=5, verbose_name='puntuación de riesgo')),
                ('probability', models.DecimalField(decimal_places=2, help_text='Probabilidad de que el riesgo se materialice (0-100%)', max_digits=5, verbose_name='probabilidad')),
                ('potential_impact', models.DecimalField(decimal_places=2, help_text='Impacto financiero estimado si se materializa', max_digits=15, verbose_name='impacto potencial')),
                ('risk_factors', models.JSONField(default=dict, help_text='Factores que contribuyen al riesgo', verbose_name='factores de riesgo')),
                ('mitigation_actions', models.JSONField(default=list, help_text='Acciones recomendadas para mitigar el riesgo', verbose_name='acciones de mitigación')),
                ('assessment_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de evaluación')),
                ('valid_until', models.DateTimeField(help_text='Cuándo debe reevaluarse este riesgo', verbose_name='válido hasta')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='evaluado por')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='fintech.credit', verbose_name='crédito')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='fintech.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evaluación de riesgo',
                'verbose_name_plural': 'evaluaciones de riesgo',
                'ordering': ['-risk_score', '-assessment_date'],
                'indexes': [models.Index(fields=['risk_type', 'risk_level'], name='forecasting_risk_ty_92740c_idx'), models.Index(fields=['assessment_date'], name='forecasting_assessm_ffa12d_idx'), models.Index(fields=['valid_until'], name='forecasting_valid_u_6f62c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('payment_date', 'Fecha de próximo pago'), ('completion_date', 'Fecha de completación'), ('default_risk', 'Riesgo de impago'), ('payment_amount', 'Monto de próximo pago')], max_length=20, verbose_name='tipo de predicción')),
                ('predicted_date', models.DateField(blank=True, help_text='Para predicciones de fechas', null=True, verbose_name='fecha predicha')),
                ('predicted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Para predicciones de montos', max_digits=12, null=True, verbose_name='monto predicho')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 = Sin riesgo, 100.00 = Alto riesgo', max_digits=5, null=True, verbose_name='puntuación de riesgo')),
                ('confidence_level', models.CharField(choices=[('high', 'Alta (>80%)'), ('medium', 'Media (60-80%)'), ('low', 'Baja (<60%)')], default='medium', max_length=10, verbose_name='nivel de confianza')),
                ('confidence_percentage', models.DecimalField(decimal_places=2, help_text='0.00-100.00', max_digits=5, verbose_name='porcentaje de confianza')),
                ('model_version', models.CharField(default='1.0', max_length=50, verbose_name='versión del modelo')),
                ('features_used', models.JSONField(default=dict, help_text='Factores considerados en la predicción', verbose_name='características utilizadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('expires_at', models.DateTimeField(help_text='Cuándo la predicción deja de ser válida', verbose_name='fecha de expiración')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fintech.credit', verbose_name='crédito')),
            ],
            options={
                'verbose_name': 'predicción de crédito',
                'verbose_name_plural': 'predicciones de créditos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['credit', 'prediction_type'], name='forecasting_credit__7966aa_idx'), models.Index(fields=['created_at'], name='forecasting_created_f5597a_idx'), models.Index(fields=['expires_at'], name='forecasting_expires_c00d58_idx')],
            },
        ),
    ]
