# Generated by Django 4.2.16 on 2025-08-08 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='assessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_forecast_risks', to=settings.AUTH_USER_MODEL, verbose_name='evaluado por'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
