# Generated by Django 4.2.16 on 2025-08-08 00:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintech', '0006_remove_interestratecategory_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia total esperada: (precio - costo) + intereses', max_digits=12, verbose_name='ganancia teórica total')),
                ('realized_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia efectivamente obtenida de los pagos recibidos', max_digits=12, verbose_name='ganancia realizada')),
                ('earnings_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Porcentaje de ganancia sobre el precio total (0.0000-1.0000)', max_digits=5, verbose_name='tasa de ganancia')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'ganancia de crédito',
                'verbose_name_plural': 'ganancias de créditos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EarningsAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor positivo aumenta ganancia, negativo la disminuye', max_digits=12, verbose_name='monto del ajuste')),
                ('adjustment_type', models.CharField(choices=[('interest_change', 'Cambio de interés'), ('discount', 'Descuento aplicado'), ('penalty', 'Penalización'), ('correction', 'Corrección contable'), ('manual', 'Ajuste manual')], max_length=20, verbose_name='tipo de ajuste')),
                ('reason', models.TextField(help_text='Descripción detallada del ajuste', verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'ajuste de ganancias',
                'verbose_name_plural': 'ajustes de ganancias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarningsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='inicio del período')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='fin del período')),
                ('total_theoretical_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total ganancias teóricas')),
                ('total_realized_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='total ganancias realizadas')),
                ('credits_count', models.IntegerField(default=0, verbose_name='cantidad de créditos')),
                ('avg_realization_rate', models.DecimalField(decimal_places=2, help_text='Porcentaje promedio de ganancias realizadas', max_digits=5, verbose_name='tasa promedio de realización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'métrica de ganancias',
                'verbose_name_plural': 'métricas de ganancias',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='revenue_ear_period__c044f1_idx'), models.Index(fields=['created_at'], name='revenue_ear_created_69d38a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='earningsmetrics',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gt', models.F('period_start'))), name='valid_earnings_period_range'),
        ),
        migrations.AddField(
            model_name='earningsadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='earningsadjustment',
            name='credit_earnings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='revenue.creditearnings', verbose_name='ganancias del crédito'),
        ),
        migrations.AddField(
            model_name='creditearnings',
            name='credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_detail', to='fintech.credit', verbose_name='crédito'),
        ),
        migrations.AddIndex(
            model_name='earningsadjustment',
            index=models.Index(fields=['credit_earnings', 'created_at'], name='revenue_ear_credit__dbf8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='earningsadjustment',
            index=models.Index(fields=['adjustment_type'], name='revenue_ear_adjustm_24ea8a_idx'),
        ),
        migrations.AddIndex(
            model_name='creditearnings',
            index=models.Index(fields=['credit'], name='revenue_cre_credit__89bef6_idx'),
        ),
        migrations.AddIndex(
            model_name='creditearnings',
            index=models.Index(fields=['updated_at'], name='revenue_cre_updated_ed7966_idx'),
        ),
    ]
