# Generated by Django 4.2.16 on 2025-09-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0008_alter_address_user_alter_credit_registered_by_and_more'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_adjustments', to='fintech.user', verbose_name='creado por'),
        ),
    ]
