# Generated by Django 4.2.16 on 2025-08-17 17:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialControlMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='monto total en mora')),
                ('overdue_credits_count', models.IntegerField(default=0, verbose_name='número de créditos en mora')),
                ('days_in_default', models.IntegerField(default=0, verbose_name='días en mora')),
                ('max_days_overdue', models.IntegerField(default=0, verbose_name='máximo días en mora')),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='low', max_length=10, verbose_name='nivel de riesgo')),
                ('risk_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='puntuación de riesgo')),
                ('payment_frequency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='frecuencia de pagos (por mes)')),
                ('avg_payment_delay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='retraso promedio de pagos (días)')),
                ('default_history', models.JSONField(default=list, verbose_name='historial de morosidad')),
                ('last_calculation', models.DateTimeField(auto_now=True, verbose_name='último cálculo')),
                ('calculation_metadata', models.JSONField(default=dict, verbose_name='metadatos de cálculo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'métrica de control financiero',
                'verbose_name_plural': 'métricas de control financiero',
                'ordering': ['-risk_score', '-total_overdue_amount'],
                'indexes': [models.Index(fields=['user'], name='insights_fi_user_id_55b8ef_idx'), models.Index(fields=['risk_level'], name='insights_fi_risk_le_0ce1a1_idx'), models.Index(fields=['risk_score'], name='insights_fi_risk_sc_b952b2_idx'), models.Index(fields=['total_overdue_amount'], name='insights_fi_total_o_e3f162_idx'), models.Index(fields=['last_calculation'], name='insights_fi_last_ca_3828bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('payment_overdue', 'Pago vencido'), ('multiple_overdue', 'Múltiples pagos vencidos'), ('risk_increase', 'Incremento de riesgo'), ('payment_pattern_change', 'Cambio en patrón de pagos'), ('credit_limit_exceeded', 'Límite de crédito excedido'), ('recovery_opportunity', 'Oportunidad de recuperación')], max_length=25, verbose_name='tipo de alerta')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta'), ('expired', 'Expirada')], default='active', max_length=15, verbose_name='estado')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('alert_data', models.JSONField(default=dict, verbose_name='datos de la alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de reconocimiento')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de expiración')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='notificación enviada')),
                ('notification_channels', models.JSONField(default=list, verbose_name='canales de notificación')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'alerta financiera',
                'verbose_name_plural': 'alertas financieras',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'alert_type'], name='insights_fi_user_id_6b689d_idx'), models.Index(fields=['priority', 'status'], name='insights_fi_priorit_f32d3a_idx'), models.Index(fields=['created_at'], name='insights_fi_created_d5012e_idx'), models.Index(fields=['expires_at'], name='insights_fi_expires_6dd0e5_idx'), models.Index(fields=['assigned_to'], name='insights_fi_assigne_32e519_idx')],
            },
        ),
        migrations.CreateModel(
            name='DefaultersReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('custom', 'Personalizado')], max_length=15, verbose_name='tipo de reporte')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='fecha del reporte')),
                ('total_defaulters', models.IntegerField(default=0, verbose_name='total de morosos')),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='monto total en mora')),
                ('avg_days_overdue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='promedio días en mora')),
                ('low_risk_count', models.IntegerField(default=0, verbose_name='bajo riesgo')),
                ('medium_risk_count', models.IntegerField(default=0, verbose_name='riesgo medio')),
                ('high_risk_count', models.IntegerField(default=0, verbose_name='alto riesgo')),
                ('critical_risk_count', models.IntegerField(default=0, verbose_name='riesgo crítico')),
                ('defaulters_data', models.JSONField(default=list, verbose_name='datos de morosos')),
                ('risk_distribution', models.JSONField(default=dict, verbose_name='distribución de riesgo')),
                ('recovery_potential', models.JSONField(default=dict, verbose_name='potencial de recuperación')),
                ('generation_metadata', models.JSONField(default=dict, verbose_name='metadatos de generación')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='generado por')),
            ],
            options={
                'verbose_name': 'reporte de morosos',
                'verbose_name_plural': 'reportes de morosos',
                'ordering': ['-report_date', '-report_type'],
                'indexes': [models.Index(fields=['report_type', 'report_date'], name='insights_de_report__05c2d8_idx'), models.Index(fields=['total_defaulters'], name='insights_de_total_d_971015_idx'), models.Index(fields=['total_overdue_amount'], name='insights_de_total_o_7769d7_idx'), models.Index(fields=['generated_by'], name='insights_de_generat_3bc4b6_idx')],
            },
        ),
    ]
